# Generated by Django 4.2 on 2023-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoterequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
