# Generated by Django 4.2 on 2023-05-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='status',
        ),
    ]
