# Generated by Django 4.2 on 2023-05-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remoterequest_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_remote',
        ),
    ]
