# Generated by Django 4.2 on 2023-05-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_delete_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='absent_days',
            field=models.ManyToManyField(blank=True, to='manager.absentday'),
        ),
    ]
