# Generated by Django 4.2 on 2023-05-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_absentday_employee_absent_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='absent_days',
        ),
        migrations.DeleteModel(
            name='AbsentDay',
        ),
    ]
