# Generated by Django 4.2 on 2023-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_employee_absent_days_delete_absentday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='absences',
            field=models.ManyToManyField(blank=True, to='manager.absence'),
        ),
    ]
