# Generated by Django 4.2 on 2023-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_absence_employee_absences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absence',
            new_name='AbsenceDay',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='absences',
        ),
        migrations.AddField(
            model_name='employee',
            name='absence_days',
            field=models.ManyToManyField(blank=True, to='manager.absenceday'),
        ),
    ]
