# Generated by Django 4.2 on 2023-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_rename_absence_absenceday_remove_employee_absences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='absence_days',
        ),
        migrations.AddField(
            model_name='employee',
            name='absent_days',
            field=models.ManyToManyField(blank=True, related_name='absent_employees', to='manager.remoteday'),
        ),
        migrations.DeleteModel(
            name='AbsenceDay',
        ),
    ]
