# Generated by Django 4.2 on 2023-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_employee_absence_days_employee_absent_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='absent_days',
        ),
        migrations.AddField(
            model_name='employee',
            name='absences',
            field=models.ManyToManyField(blank=True, related_name='absent_employees', to='manager.remoteday'),
        ),
    ]
