# Generated by Django 4.2 on 2023-06-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_employee_absent_days_employee_absences'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='absences',
        ),
        migrations.AddField(
            model_name='employee',
            name='absence_days',
            field=models.ManyToManyField(blank=True, to='manager.absenceday'),
        ),
    ]
