# Generated by Django 4.2 on 2023-06-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_absenceday_remove_employee_absences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='absence_days',
        ),
        migrations.DeleteModel(
            name='AbsenceDay',
        ),
    ]
