# Dockerfile.nginx

# Pull nginx from Docker Hub
FROM nginx:1.19

# remove default configuration
RUN rm /etc/nginx/conf.d/default.conf

# replace with our configuration
COPY nginx.conf /etc/nginx/conf.d/
